### ISSUE TITLE
createMutationKeys with schema does not expose type mutationFn like the createQueryKeys function does

### ISSUE THREAD

**Issue by siteassist-benjamin** [lukemorales/query-key-factory#63] opened 2023-05-15 10:08 UTC
We need to access and reuse the `mutationFn` from one of the mutationKeys definitions. However the only property exposed by the library for createMutationKeys is the `mutationKey`.

This is not a problem with the `createQueryKeys` function - see examples below:

![Screenshot 2023-05-15 at 12 07 14](https://github.com/lukemorales/query-key-factory/assets/102516120/c9cf6d39-9e6f-4ee2-a212-8e893f749d2c)
![Screenshot 2023-05-15 at 12 07 04](https://github.com/lukemorales/query-key-factory/assets/102516120/bff5e64b-8f02-4f5f-a3be-e91ba3bbab31)

I have tried looking into where this would need to change but I am a little lost as the typing system is very complex. Any help would be deeply appreciated 🙏

**Comment by lukemorales** [comment] 2023-05-17 19:34
@siteassist-benjamin the `createMutationKeys` types are in fact broken, it's a now issue #55 but I didn't have the time yet to fix it. I'll just close the issue as a duplicate of #55, but feel free to add any comments on that issue

**Closed by lukemorales** 2023-05-17 19:34 UTC
